# Generated by Django 5.2.3 on 2025-06-24 18:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(max_length=100, unique=True, verbose_name='List Title')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_item_title', models.CharField(max_length=100, verbose_name='List Item Title')),
                ('list_item_description', models.CharField(max_length=1000, verbose_name='List Item Description')),
                ('created_date', models.DateField(auto_now=True)),
                ('due_date', models.DateField(default=datetime.datetime(2025, 7, 1, 18, 34, 1, 813451))),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.todolist')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
