# Generated by Django 5.2.3 on 2025-06-24 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 1, 18, 38, 30, 920064)),
        ),
        migrations.AlterUniqueTogether(
            name='todoitem',
            unique_together={('list_item_title', 'todo_list')},
        ),
    ]
