# Generated by Django 5.2.3 on 2025-06-24 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todoitem_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='list_item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='list_item_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='list_title',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='todoitem',
            unique_together={('title', 'todo_list')},
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 1, 18, 40, 40, 299094)),
        ),
    ]
